In [47]:
import pandas as pd
frais = pd.read_csv('data/raw/frais.csv')
frais

,PORTFOLIO_IK,SECURITY_ISIN,SECURITY_NAME,DATE_FRAIS,TYPE_FRAIS,MONTANT_FRAIS,DEVISE_FRAIS
0,188,FR0010505578,EdR SICAV - Euro Sustainable Equity A - EUR,2020-09-30 00:00:00.000,FRAIS_FIXE,-5546.08,EUR
1,188,FR0010505578,EdR SICAV - Euro Sustainable Equity A - EUR,2020-09-30 00:00:00.000,FRAIS_VARIABLE,20176.82,EUR
2,188,FR0010505578,EdR SICAV - Euro Sustainable Equity A - EUR,2020-09-30 00:00:00.000,FRAIS_GLOBAL,-312.86,EUR
3,188,FR0010505578,EdR SICAV - Euro Sustainable Equity A - EUR,2020-09-30 00:00:00.000,FRAIS_ACQUIS,-19208.03,EUR
4,188,FR0010505578,EdR SICAV - Euro Sustainable Equity A - EUR,2020-10-01 00:00:00.000,FRAIS_GLOBAL,-315.39,EUR
...,...,...,...,...,...,...,...
129873,80398,LU2596456975,EdR Fund Big Data CRM - EUR,2024-09-30 00:00:00.000,FRAIS_FIXE,-14085.55,EUR
129874,82903,LU2678233599,EdR Fund Emerging Credit R - USD,2024-09-27 00:00:00.000,FRAIS_GLOBAL,-6.36,USD
129875,82903,LU2678233599,EdR Fund Emerging Credit R - USD,2024-09-27 00:00:00.000,FRAIS_FIXE,-1.97,USD
129876,82903,LU2678233599,EdR Fund Emerging Credit R - USD,2024-09-30 00:00:00.000,FRAIS_GLOBAL,-1.25,USD
129877,82903,LU2678233599,EdR Fund Emerging Credit R - USD,2024-09-30 00:00:00.000,FRAIS_FIXE,-5.91,USD

In [48]:
frais.SECURITY_NAME.unique()

array(['EdR SICAV - Euro Sustainable Equity A - EUR',
       'EdR SICAV - Euro Sustainable Equity I - EUR',
       'EdR SICAV - Euro Sustainable Equity K - EUR',
       'EdR SICAV - Euro Sustainable Equity R - EUR',
       'EdR SICAV - Euro Sustainable Equity CR - EUR',
       'EdR SICAV - Euro Sustainable Equity B - EUR',
       'EdR SICAV - Euro Sustainable Equity CRD - EUR',
       'EdR SICAV - Euro Sustainable Equity J - EUR',
       'EdR SICAV - Euro Sustainable Equity O - EUR',
       'EdR SICAV - Euro Sustainable Equity P - EUR',
       'EdR SICAV - Euro Sustainable Equity A - USD',
       'EdR Fund Emerging Credit A - USD',
       'EdR Fund Emerging Credit A - EUR (H)',
       'EdR Fund Emerging Credit B - USD',
       'EdR Fund Emerging Credit B - EUR (H)',
       'EdR Fund Emerging Credit I - USD',
       'EdR Fund Emerging Credit I - EUR (H)',
       'EdR Fund Euro High Yield I - EUR',
       'EdR Fund Euro High Yield B - EUR',
       'EdR Fund Euro High Yield A - USD (H)',
       'EdR Fund Euro High Yield A - EUR',
       'EdR Fund Euro High Yield R - EUR',
       'EdR Fund Euro High Yield O - EUR',
       'EdR Fund Euro High Yield N - EUR',
       'EdR Fund Euro High Yield J - EUR',
       'EdR Fund Euro High Yield A - CHF',
       'EdR Fund Emerging Credit CR - EUR (H)',
       'EdR Fund Big Data A - EUR', 'EdR Fund Big Data A - USD',
       'EdR Fund Big Data A - CHF', 'EdR Fund Big Data I - EUR',
       'EdR Fund Big Data I - USD', 'EdR Fund Big Data K - EUR',
       'EdR Fund Big Data N - EUR', 'EdR Fund Big Data N - USD',
       'EdR Fund Big Data N CHF', 'EdR Fund Big Data R - EUR',
       'EdR Fund Big Data R - USD', 'EdR Fund Big Data B - EUR',
       'EdR Fund Euro High Yield I - CHF (H)',
       'EdR Fund Emerging Credit KD - USD',
       'EdR Fund Emerging Credit KD - EUR (H)',
       'EdR Fund Emerging Credit K - USD',
       'EdR Fund Euro High Yield K - EUR',
       'EdR Fund Euro High Yield CR - EUR', 'EdR Fund Big Data CR - EUR',
       'EdR Fund Big Data CRD - EUR', 'EdR Fund Emerging Credit CR - USD',
       'EdR Fund Big Data CR - USD', 'EdR Fund Big Data CRD - USD',
       'EdR Fund Emerging Credit A - CHF (H)',
       'EdR Fund Emerging Credit I - CHF (H)',
       'EdR Fund Big Data J - USD', 'EdR Fund Big Data N2 - EUR',
       'EdR Fund Big Data P - EUR', 'EdR Fund Big Data P - USD',
       'EdR Fund Big Data CRM - EUR', 'EdR Fund Emerging Credit R - USD'],
      dtype=object)

In [49]:
frais = pd.read_csv('data/raw/frais.csv')
filtered_frais = frais[frais['SECURITY_NAME'].isin([
    'EdR Fund Euro High Yield I - EUR',
    'EdR Fund Euro High Yield B - EUR',
    'EdR Fund Euro High Yield A - USD (H)',
    'EdR Fund Euro High Yield A - EUR',
    'EdR Fund Euro High Yield R - EUR',
    'EdR Fund Euro High Yield O - EUR',
    'EdR Fund Euro High Yield N - EUR',
    'EdR Fund Euro High Yield J - EUR',
    'EdR Fund Euro High Yield A - CHF',
    'EdR Fund Euro High Yield I - CHF (H)',
    'EdR Fund Euro High Yield K - EUR',
    'EdR Fund Euro High Yield CR - EUR',
])]
filtered_frais.DATE_FRAIS = filtered_frais.DATE_FRAIS.str.replace(' 00:00:00.000', '').str.strip()
filtered_frais.DATE_FRAIS = pd.to_datetime(filtered_frais.DATE_FRAIS, format='%Y-%m-%d')
filtered_frais['month'] = filtered_frais.DATE_FRAIS.dt.month
filtered_frais

C:\Users\maelm\AppData\Local\Temp\ipykernel_2360\2389477236.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_frais.DATE_FRAIS = filtered_frais.DATE_FRAIS.str.replace(' 00:00:00.000', '').str.strip()
C:\Users\maelm\AppData\Local\Temp\ipykernel_2360\2389477236.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_frais.DATE_FRAIS = pd.to_datetime(filtered_frais.DATE_FRAIS, format='%Y-%m-%d')
C:\Users\maelm\AppData\Local\Temp\ipykernel_2360\2389477236.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_frais['month'] = filtered_frais.DATE_FRAIS.dt.month

,PORTFOLIO_IK,SECURITY_ISIN,SECURITY_NAME,DATE_FRAIS,TYPE_FRAIS,MONTANT_FRAIS,DEVISE_FRAIS,month
35345,18502,LU1160362742,EdR Fund Euro High Yield I - EUR,2020-09-30,FRAIS_FIXE,-176.28,EUR,9
35346,18502,LU1160362742,EdR Fund Euro High Yield I - EUR,2020-09-30,FRAIS_VARIABLE,-1801.54,EUR,9
35347,18502,LU1160362742,EdR Fund Euro High Yield I - EUR,2020-09-30,FRAIS_GLOBAL,-52.00,EUR,9
35348,18502,LU1160362742,EdR Fund Euro High Yield I - EUR,2020-10-01,FRAIS_GLOBAL,-83.55,EUR,10
35349,18502,LU1160362742,EdR Fund Euro High Yield I - EUR,2020-10-01,FRAIS_FIXE,-176.79,EUR,10
...,...,...,...,...,...,...,...,...
101008,45519,LU1781816373,EdR Fund Euro High Yield CR - EUR,2024-09-26,FRAIS_GLOBAL,-5.02,EUR,9
101009,45519,LU1781816373,EdR Fund Euro High Yield CR - EUR,2024-09-27,FRAIS_FIXE,-22.21,EUR,9
101010,45519,LU1781816373,EdR Fund Euro High Yield CR - EUR,2024-09-27,FRAIS_GLOBAL,-4.56,EUR,9
101011,45519,LU1781816373,EdR Fund Euro High Yield CR - EUR,2024-09-30,FRAIS_GLOBAL,-14.09,EUR,9
101012,45519,LU1781816373,EdR Fund Euro High Yield CR - EUR,2024-09-30,FRAIS_FIXE,-66.66,EUR,9

In [52]:
pivoted_frais = filtered_frais.pivot_table(index='DATE_FRAIS', columns='TYPE_FRAIS', values='MONTANT_FRAIS', aggfunc='sum').reset_index()
pivoted_frais

TYPE_FRAIS DATE_FRAIS  FRAIS_ACQUIS  FRAIS_FIXE  FRAIS_GLOBAL  FRAIS_VARIABLE
0          2020-09-30           NaN    -3118.41       -619.63       -13934.93
1          2020-10-01        -24.36    -3128.23       -858.13         2720.81
2          2020-10-02         -8.44    -3129.61       -783.27        -1349.31
3          2020-10-05       -152.01    -9396.61      -1875.32        -1546.56
4          2020-10-06        -80.43    -3135.24       -634.74         1409.00
...               ...           ...         ...           ...             ...
996        2024-09-24           NaN    -5285.24      -1094.46             NaN
997        2024-09-25           NaN    -5297.18      -1189.11             NaN
998        2024-09-26           NaN    -5300.38      -1053.62             NaN
999        2024-09-27           NaN    -5303.79       -953.84             NaN
1000       2024-09-30           NaN   -15914.97      -2950.22             NaN

[1001 rows x 5 columns]

In [53]:
pivoted_frais['year'] = pivoted_frais['DATE_FRAIS'].dt.year
pivoted_frais['month'] = pivoted_frais['DATE_FRAIS'].dt.month
pivoted_frais

TYPE_FRAIS,DATE_FRAIS,FRAIS_ACQUIS,FRAIS_FIXE,FRAIS_GLOBAL,FRAIS_VARIABLE,year,month
0,2020-09-30,NaN,-3118.41,-619.63,-13934.93,2020,9
1,2020-10-01,-24.36,-3128.23,-858.13,2720.81,2020,10
2,2020-10-02,-8.44,-3129.61,-783.27,-1349.31,2020,10
3,2020-10-05,-152.01,-9396.61,-1875.32,-1546.56,2020,10
4,2020-10-06,-80.43,-3135.24,-634.74,1409.00,2020,10
...,...,...,...,...,...,...,...
996,2024-09-24,NaN,-5285.24,-1094.46,NaN,2024,9
997,2024-09-25,NaN,-5297.18,-1189.11,NaN,2024,9
998,2024-09-26,NaN,-5300.38,-1053.62,NaN,2024,9
999,2024-09-27,NaN,-5303.79,-953.84,NaN,2024,9
1000,2024-09-30,NaN,-15914.97,-2950.22,NaN,2024,9

In [54]:
# Group by year and month, then sum each type of frais
monthly_sum_by_year = pivoted_frais.groupby(['year', 'month'])[['FRAIS_FIXE','FRAIS_ACQUIS','FRAIS_GLOBAL','FRAIS_VARIABLE']].sum().reset_index()
monthly_sum_by_year

TYPE_FRAIS,year,month,FRAIS_FIXE,FRAIS_ACQUIS,FRAIS_GLOBAL,FRAIS_VARIABLE
0,2020,9,-3118.41,0.00,-619.63,-1.393493e+04
1,2020,10,-95092.44,-3183.54,-38383.93,1.804947e+04
2,2020,11,-101551.86,-9719.17,-24492.05,-1.195374e+05
3,2020,12,-100330.69,-24966.31,-36973.63,3.686950e+03
4,2021,1,-92808.95,-23646.87,-23120.60,7.652019e+04
5,2021,2,-88021.44,-3515.85,-19686.21,-4.160371e+04
6,2021,3,-103587.28,-9502.53,-25766.15,-3.927598e+04
7,2021,4,-94969.09,-7216.09,-21125.13,-9.728610e+04
8,2021,5,-99717.92,-1498.64,-21009.81,2.946229e+04
9,2021,6,-98853.49,-6502.19,-24595.61,6.986100e+02
10,2021,7,-98650.14,-63.00,-23639.84,-1.460000e+00
11,2021,8,-106997.75,0.00,-26397.85,0.000000e+00
12,2021,9,-100555.82,0.00,-22154.86,-4.004000e+01
13,2021,10,-96138.24,0.00,-27020.77,4.004000e+01
14,2021,11,-106045.90,0.00,-25149.83,0.000000e+00
15,2021,12,-102671.89,0.00,-27897.22,-3.431000e+01
16,2022,1,-103401.20,0.00,-22963.31,3.386000e+01
17,2022,2,-91312.78,0.00,-24996.94,0.000000e+00
18,2022,3,-96801.21,0.00,-21648.37,0.000000e+00
19,2022,4,-89653.15,-996.53,-20700.18,-1.253856e+05
20,2022,5,-95243.96,-5569.25,-20760.99,-4.788064e+04
21,2022,6,-85281.58,-7024.41,-19047.10,-1.545460e+05
22,2022,7,-80307.34,-4526.50,-19726.58,7.880230e+04
23,2022,8,-116832.89,-6360.94,-26817.04,4.681659e+04
24,2022,9,-104476.73,-8549.34,-23299.74,-8.615961e+04
25,2022,10,-102819.44,-5128.49,-23374.96,3.692193e+04
26,2022,11,-103185.05,-2685.59,-22996.83,2.069901e+05
27,2022,12,-106393.51,-169.31,-28187.40,1.999745e+04
28,2023,1,-121210.17,-4378.89,-29347.30,2.091205e+04
29,2023,2,-117836.03,-14.16,-32335.79,1.735910e+03
30,2023,3,-129474.37,-923.49,-34121.35,5.434000e+01
31,2023,4,-122161.96,0.00,-28244.48,8.690300e+02
32,2023,5,-147802.97,0.00,-33103.75,6.933500e+02
33,2023,6,-136330.25,0.00,-32095.12,6.813000e+01
34,2023,7,-140433.68,0.00,-31976.51,0.000000e+00
35,2023,8,-136555.11,0.00,-30655.36,0.000000e+00
36,2023,9,-132724.89,0.00,-31156.27,0.000000e+00
37,2023,10,-135773.97,0.00,-33566.69,0.000000e+00
38,2023,11,-131131.36,0.00,-33866.47,0.000000e+00
39,2023,12,-130275.87,0.00,-33763.75,0.000000e+00
40,2024,1,-148956.67,0.00,-34002.69,0.000000e+00
41,2024,2,-135067.29,0.00,-35700.94,0.000000e+00
42,2024,3,-144148.06,0.00,-35407.89,0.000000e+00
43,2024,4,-142706.75,0.00,-34951.06,0.000000e+00
44,2024,5,-150316.55,0.00,-39233.57,0.000000e+00
45,2024,6,-138239.27,0.00,-39384.55,0.000000e+00
46,2024,7,-163863.79,0.00,-42880.79,-1.776357e-15
47,2024,8,-151032.22,0.00,-32822.44,-1.540000e+00
48,2024,9,-160316.83,0.00,-38083.46,1.540000e+00

In [55]:
monthly_sum_by_year['date'] = pd.to_datetime(monthly_sum_by_year[['year', 'month']].assign(day=1)) + pd.offsets.MonthEnd(0)
monthly_sum_by_year.drop(['year', 'month'], axis=1, inplace=True)
monthly_sum_by_year

TYPE_FRAIS  FRAIS_FIXE  FRAIS_ACQUIS  FRAIS_GLOBAL  FRAIS_VARIABLE       date
0             -3118.41          0.00       -619.63   -1.393493e+04 2020-09-30
1            -95092.44      -3183.54     -38383.93    1.804947e+04 2020-10-31
2           -101551.86      -9719.17     -24492.05   -1.195374e+05 2020-11-30
3           -100330.69     -24966.31     -36973.63    3.686950e+03 2020-12-31
4            -92808.95     -23646.87     -23120.60    7.652019e+04 2021-01-31
5            -88021.44      -3515.85     -19686.21   -4.160371e+04 2021-02-28
6           -103587.28      -9502.53     -25766.15   -3.927598e+04 2021-03-31
7            -94969.09      -7216.09     -21125.13   -9.728610e+04 2021-04-30
8            -99717.92      -1498.64     -21009.81    2.946229e+04 2021-05-31
9            -98853.49      -6502.19     -24595.61    6.986100e+02 2021-06-30
10           -98650.14        -63.00     -23639.84   -1.460000e+00 2021-07-31
11          -106997.75          0.00     -26397.85    0.000000e+00 2021-08-31
12          -100555.82          0.00     -22154.86   -4.004000e+01 2021-09-30
13           -96138.24          0.00     -27020.77    4.004000e+01 2021-10-31
14          -106045.90          0.00     -25149.83    0.000000e+00 2021-11-30
15          -102671.89          0.00     -27897.22   -3.431000e+01 2021-12-31
16          -103401.20          0.00     -22963.31    3.386000e+01 2022-01-31
17           -91312.78          0.00     -24996.94    0.000000e+00 2022-02-28
18           -96801.21          0.00     -21648.37    0.000000e+00 2022-03-31
19           -89653.15       -996.53     -20700.18   -1.253856e+05 2022-04-30
20           -95243.96      -5569.25     -20760.99   -4.788064e+04 2022-05-31
21           -85281.58      -7024.41     -19047.10   -1.545460e+05 2022-06-30
22           -80307.34      -4526.50     -19726.58    7.880230e+04 2022-07-31
23          -116832.89      -6360.94     -26817.04    4.681659e+04 2022-08-31
24          -104476.73      -8549.34     -23299.74   -8.615961e+04 2022-09-30
25          -102819.44      -5128.49     -23374.96    3.692193e+04 2022-10-31
26          -103185.05      -2685.59     -22996.83    2.069901e+05 2022-11-30
27          -106393.51       -169.31     -28187.40    1.999745e+04 2022-12-31
28          -121210.17      -4378.89     -29347.30    2.091205e+04 2023-01-31
29          -117836.03        -14.16     -32335.79    1.735910e+03 2023-02-28
30          -129474.37       -923.49     -34121.35    5.434000e+01 2023-03-31
31          -122161.96          0.00     -28244.48    8.690300e+02 2023-04-30
32          -147802.97          0.00     -33103.75    6.933500e+02 2023-05-31
33          -136330.25          0.00     -32095.12    6.813000e+01 2023-06-30
34          -140433.68          0.00     -31976.51    0.000000e+00 2023-07-31
35          -136555.11          0.00     -30655.36    0.000000e+00 2023-08-31
36          -132724.89          0.00     -31156.27    0.000000e+00 2023-09-30
37          -135773.97          0.00     -33566.69    0.000000e+00 2023-10-31
38          -131131.36          0.00     -33866.47    0.000000e+00 2023-11-30
39          -130275.87          0.00     -33763.75    0.000000e+00 2023-12-31
40          -148956.67          0.00     -34002.69    0.000000e+00 2024-01-31
41          -135067.29          0.00     -35700.94    0.000000e+00 2024-02-29
42          -144148.06          0.00     -35407.89    0.000000e+00 2024-03-31
43          -142706.75          0.00     -34951.06    0.000000e+00 2024-04-30
44          -150316.55          0.00     -39233.57    0.000000e+00 2024-05-31
45          -138239.27          0.00     -39384.55    0.000000e+00 2024-06-30
46          -163863.79          0.00     -42880.79   -1.776357e-15 2024-07-31
47          -151032.22          0.00     -32822.44   -1.540000e+00 2024-08-31
48          -160316.83          0.00     -38083.46    1.540000e+00 2024-09-30

In [56]:
monthly_sum_by_year.to_csv('data/processed/monthly_sum_by_year.csv', index=False)